dependencies:
  - name: mariadb
    version: 6.4.3
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: zookeeper
    version: 3.0.3
    repository: https://charts.bitnami.com/bitnami
