mariadb:
  fullnameOverride: mariadb
  metrics:
    enabled: false
  slave:
    replicas: 2

zookeeper:
  fullnameOverride: zookeeper
  metrics:
    enabled: false
  snapshot:
    trust:
      empty: true
  config: |-
    tickTime=2000
    initLimit=10
    syncLimit=5
    dataDir=/bitnami/zookeeper/data
    clientPort=2181
    maxClientCnxns=60
    server.1=zookeeper-0.zookeeper-headless.default.svc:2888:3888
    server.2=zookeeper-1.zookeeper-headless.default.svc:2888:3888
    server.3=zookeeper-2.zookeeper-headless.default.svc:2888:3888

  replicaCount: 3

config:
  zuul: |-
  main: |-
  ssh:
    zuul:
    zuulPub:
    admin:
    adminPub:
  gerritHost: gerrit

ingress:
  enabled: false

host_key:
  enabled: false
