apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: executor
  name: executor
spec:
  ports:
  - name: "7900"
    port: 7900
    targetPort: 7900
  selector:
    app: executor
  type: ClusterIP
