apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: scheduler
  name: scheduler
spec:
  ports:
  - name: "4730"
    port: 4730
    targetPort: 4730
  selector:
    app: scheduler
