apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
data:
  zuul: |-
    {{- with .Values.config }}
    {{ .ssh.zuul | b64enc }}
  zuul.pub: |-
    {{ .ssh.zuulPub | b64enc }}
  admin: |-
    {{ .ssh.admin | b64enc }}
  admin.pub: |-
    {{ .ssh.adminPub | b64enc }}
  nodepool: |-
    {{ .ssh.nodepool | b64enc }}
  nodepool.pub: |-
    {{ .ssh.nodepoolPub | b64enc }}
  mcp-gerrit: |-
    {{ .ssh.mcpgerrit | b64enc }}
  mcp-gerrit.pub: |-
    {{ .ssh.mcpgerritPub | b64enc }}
    {{ end }}
