apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
data:
  zuul: |-
    {{- with .Values.config }}
    {{ .ssh.zuul | b64enc }}
  zuul.pub: |-
    {{ .ssh.zuulPub | b64enc }}
  admin: |-
    {{ .ssh.admin | b64enc }}
  admin.pub: |-
    {{ .ssh.adminPub | b64enc }}
    {{ end }}
