apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
    nodePort: 30090
  selector:
    io.kompose.service: web
  type: NodePort
status:
  loadBalancer: {}
